package com.github.sankowskiwojciech.courseslessons.service.lesson.validator;

import com.google.common.collect.ImmutableSet;
import lombok.AccessLevel;
import lombok.NoArgsConstructor;

import java.util.Set;

@NoArgsConstructor(access = AccessLevel.PRIVATE)
public final class ValidFileMIMETypes {
    public static final Set<String> VALID_FILE_MIME_TYPES = ImmutableSet.of(
            "application/json",
            "application/vnd.ms-word",
            "application/msword",
            "application/msword2",
            "application/msword5",
            "application/onenote",
            "application/onenote;format=one",
            "application/onenote;format=onetoc2",
            "application/onenote; format=package",
            "application/pdf",
            "application/vnd.ms-spreadsheetml",
            "application/vnd.ms-wordml",
            "application/vnd.ms-word2006ml",
            "application/vnd.apple.iwork",
            "application/vnd.apple.keynote",
            "application/vnd.apple.pages",
            "application/vnd.apple.numbers",
            "application/x-tika-iworks-protected",
            "application/vnd.ms-excel",
            "application/msexcel",
            "application/vnd.ms-excel.addin.macroenabled.12",
            "application/vnd.ms-excel.sheet.macroenabled.12",
            "application/vnd.ms-excel.sheet.binary.macroenabled.12",
            "application/vnd.ms-excel.sheet.4",
            "application/vnd.ms-excel.workspace.4",
            "application/vnd.ms-excel.sheet.3",
            "application/vnd.ms-excel.workspace.3",
            "application/vnd.ms-excel.sheet.2",
            "application/vnd.ms-powerpoint",
            "application/mspowerpoint",
            "application/vnd.ms-powerpoint.addin.macroenabled.12",
            "application/vnd.ms-powerpoint.presentation.macroenabled.12",
            "application/vnd.ms-powerpoint.slide.macroenabled.12",
            "application/vnd.ms-powerpoint.slideshow.macroenabled.12",
            "application/vnd.ms-powerpoint.template.macroenabled.12",
            "application/vnd.ms-word.document.macroenabled.12",
            "application/vnd.ms-word.template.macroenabled.12",
            "application/vnd.oasis.opendocument.formula",
            "application/vnd.oasis.opendocument.formula-template",
            "application/vnd.oasis.opendocument.image",
            "application/vnd.oasis.opendocument.image-template",
            "application/vnd.oasis.opendocument.presentation",
            "application/vnd.oasis.opendocument.presentation-template",
            "application/vnd.oasis.opendocument.spreadsheet",
            "application/vnd.oasis.opendocument.spreadsheet-template",
            "application/vnd.oasis.opendocument.text",
            "application/vnd.oasis.opendocument.text-master",
            "application/vnd.oasis.opendocument.text-template",
            "application/vnd.oasis.opendocument.text-web",
            "application/vnd.openxmlformats-officedocument.presentationml.presentation",
            "application/vnd.openxmlformats-officedocument.presentationml.slide",
            "application/vnd.openxmlformats-officedocument.presentationml.template",
            "application/vnd.openxmlformats-officedocument.presentationml.slideshow",
            "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
            "application/vnd.openxmlformats-officedocument.spreadsheetml.template",
            "application/vnd.ms-excel.template.macroenabled.12",
            "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
            "application/vnd.openxmlformats-officedocument.wordprocessingml.template",
            "application/x-gtar",
            "application/x-tar",
            "application/x-bzip",
            "application/x-bzip2",
            "application/gzip",
            "application/x-gzip",
            "application/x-rar-compressed",
            "application/x-rar",
            "application/x-rar-compressed;version=4",
            "application/x-rar-compressed;version=5",
            "application/zip",
            "application/x-zip-compressed",
            "application/x-7z-compressed",
            "application/zlib",
            "application/x-deflate",
            "image/bmp",
            "image/gif",
            "image/jpeg",
            "image/png",
            "image/tiff",
            "text/csv",
            "text/plain",
            "text/richtext",
            "text/x-yaml"
    );
}
